@WebApplication1_HostAddress = https://localhost:7034
### @name GetTodosInParallel

GET {{WebApplication1_HostAddress}}/GetTodosInParallel/
Accept: application/json

### @name GetTodosInSequence
GET {{WebApplication1_HostAddress}}/GetTodosInSequence/
Accept: application/json